// 生成 dist/robots.txt:AI 爬虫显式 Allow(数据源:vendored robots.json + cn-bots.json)。
// 注意:上游项目默认姿态是封禁,这里只取其 UA 清单做 Allow 反转(增补件 A1)。
// 所有爬虫(含 AI 爬虫)均屏蔽控制台/内部路径(主 spec §0 硬性约束)。
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(resolve(root, p), 'utf8'));

const site = read('src/data/pages.json').site;
const host = new URL(site).host;
const upstream = Object.keys(read('config/robots.json'));
const cn = read('config/cn-bots.json').bots.map((b) => b.ua);
const source = read('config/robots-source.json');
// 大小写不敏感去重,保留首见(上游)原始大小写(REVIEW r3 D2/R-A)
const merged = new Map();
for (const ua of [...upstream, ...cn]) {
  if (!merged.has(ua.toLowerCase())) merged.set(ua.toLowerCase(), ua);
}
const uas = [...merged.values()];

const INTERNAL_DISALLOWS = ['/console/', '/admin/', '/api/internal/'];
const disallowBlock = INTERNAL_DISALLOWS.map((p) => `Disallow: ${p}`).join('\n');

const groups = uas.map((ua) => `User-agent: ${ua}\nAllow: /\n${disallowBlock}`);

const robotsTxt = `# ${host} — AI crawler policy: allow by default
# Generated by scripts/generate-robots.mjs — DO NOT EDIT BY HAND
# UA sources: ${source.repo}@${source.commit.slice(0, 7)} (${upstream.length} UAs) + config/cn-bots.json (${cn.length} UAs)

${groups.join('\n\n')}

User-agent: *
Allow: /
${disallowBlock}

Sitemap: ${site}/sitemap.xml
`;

const dist = resolve(root, 'dist');
if (!existsSync(dist)) {
  console.error('dist/ not found — run astro build first');
  process.exit(1);
}
writeFileSync(resolve(dist, 'robots.txt'), robotsTxt);
console.log(`robots.txt generated: ${uas.length} explicit allow groups`);
